# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cryptanalysis.ui'
#
# Created: Mon Sep 16 23:36:15 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tabWidget(object):
    def setupUi(self, tabWidget):
        tabWidget.setObjectName(_fromUtf8("tabWidget"))
        tabWidget.resize(907, 718)
        self.vigenere = QtGui.QWidget()
        self.vigenere.setObjectName(_fromUtf8("vigenere"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.vigenere)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.vigenerTopPartLayout = QtGui.QHBoxLayout()
        self.vigenerTopPartLayout.setObjectName(_fromUtf8("vigenerTopPartLayout"))
        self.cypheredGroupBox_VIG = QtGui.QGroupBox(self.vigenere)
        self.cypheredGroupBox_VIG.setObjectName(_fromUtf8("cypheredGroupBox_VIG"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.cypheredGroupBox_VIG)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cypheredTextEdit_VIG = QtGui.QTextEdit(self.cypheredGroupBox_VIG)
        self.cypheredTextEdit_VIG.setObjectName(_fromUtf8("cypheredTextEdit_VIG"))
        self.horizontalLayout_2.addWidget(self.cypheredTextEdit_VIG)
        self.vigenerTopPartLayout.addWidget(self.cypheredGroupBox_VIG)
        self.bruteForceGroupBox = QtGui.QGroupBox(self.vigenere)
        self.bruteForceGroupBox.setObjectName(_fromUtf8("bruteForceGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.bruteForceGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.bruteForceButton = QtGui.QPushButton(self.bruteForceGroupBox)
        self.bruteForceButton.setObjectName(_fromUtf8("bruteForceButton"))
        self.verticalLayout.addWidget(self.bruteForceButton)
        self.lengthBruteForceLayout = QtGui.QHBoxLayout()
        self.lengthBruteForceLayout.setObjectName(_fromUtf8("lengthBruteForceLayout"))
        self.lengthFoundLabel = QtGui.QLabel(self.bruteForceGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lengthFoundLabel.sizePolicy().hasHeightForWidth())
        self.lengthFoundLabel.setSizePolicy(sizePolicy)
        self.lengthFoundLabel.setObjectName(_fromUtf8("lengthFoundLabel"))
        self.lengthBruteForceLayout.addWidget(self.lengthFoundLabel)
        self.lengthSpinBox = QtGui.QSpinBox(self.bruteForceGroupBox)
        self.lengthSpinBox.setObjectName(_fromUtf8("lengthSpinBox"))
        self.lengthBruteForceLayout.addWidget(self.lengthSpinBox)
        self.verticalLayout.addLayout(self.lengthBruteForceLayout)
        self.languageComboBox = QtGui.QComboBox(self.bruteForceGroupBox)
        self.languageComboBox.setObjectName(_fromUtf8("languageComboBox"))
        self.languageComboBox.addItem(_fromUtf8(""))
        self.languageComboBox.addItem(_fromUtf8(""))
        self.languageComboBox.addItem(_fromUtf8(""))
        self.languageComboBox.addItem(_fromUtf8(""))
        self.languageComboBox.addItem(_fromUtf8(""))
        self.languageComboBox.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.languageComboBox)
        self.keyFoundLabel = QtGui.QLabel(self.bruteForceGroupBox)
        self.keyFoundLabel.setObjectName(_fromUtf8("keyFoundLabel"))
        self.verticalLayout.addWidget(self.keyFoundLabel)
        self.tryKeyButton = QtGui.QPushButton(self.bruteForceGroupBox)
        self.tryKeyButton.setObjectName(_fromUtf8("tryKeyButton"))
        self.verticalLayout.addWidget(self.tryKeyButton)
        self.vigenerTopPartLayout.addWidget(self.bruteForceGroupBox)
        self.verticalLayout_6.addLayout(self.vigenerTopPartLayout)
        self.keyGroupBox = QtGui.QGroupBox(self.vigenere)
        self.keyGroupBox.setObjectName(_fromUtf8("keyGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.keyGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.keyLineEdit = QtGui.QLineEdit(self.keyGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyLineEdit.sizePolicy().hasHeightForWidth())
        self.keyLineEdit.setSizePolicy(sizePolicy)
        self.keyLineEdit.setObjectName(_fromUtf8("keyLineEdit"))
        self.horizontalLayout.addWidget(self.keyLineEdit)
        self.keyOffsetLabel = QtGui.QLabel(self.keyGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyOffsetLabel.sizePolicy().hasHeightForWidth())
        self.keyOffsetLabel.setSizePolicy(sizePolicy)
        self.keyOffsetLabel.setObjectName(_fromUtf8("keyOffsetLabel"))
        self.horizontalLayout.addWidget(self.keyOffsetLabel)
        self.keyOffsetSpinBox = QtGui.QSpinBox(self.keyGroupBox)
        self.keyOffsetSpinBox.setObjectName(_fromUtf8("keyOffsetSpinBox"))
        self.horizontalLayout.addWidget(self.keyOffsetSpinBox)
        self.verticalLayout_6.addWidget(self.keyGroupBox)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.decypheredTextGroupBox_VIG = QtGui.QGroupBox(self.vigenere)
        self.decypheredTextGroupBox_VIG.setObjectName(_fromUtf8("decypheredTextGroupBox_VIG"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.decypheredTextGroupBox_VIG)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.decypheredTextEdit_VIG = QtGui.QTextEdit(self.decypheredTextGroupBox_VIG)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decypheredTextEdit_VIG.sizePolicy().hasHeightForWidth())
        self.decypheredTextEdit_VIG.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.decypheredTextEdit_VIG.setFont(font)
        self.decypheredTextEdit_VIG.setReadOnly(True)
        self.decypheredTextEdit_VIG.setObjectName(_fromUtf8("decypheredTextEdit_VIG"))
        self.horizontalLayout_3.addWidget(self.decypheredTextEdit_VIG)
        self.horizontalLayout_11.addWidget(self.decypheredTextGroupBox_VIG)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.vigenere)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_3.addWidget(self.checkBox)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.plainTextAttackGroupBox = QtGui.QGroupBox(self.vigenere)
        self.plainTextAttackGroupBox.setObjectName(_fromUtf8("plainTextAttackGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.plainTextAttackGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cypheredTextLayout = QtGui.QHBoxLayout()
        self.cypheredTextLayout.setObjectName(_fromUtf8("cypheredTextLayout"))
        self.cyphereTextLabel = QtGui.QLabel(self.plainTextAttackGroupBox)
        self.cyphereTextLabel.setObjectName(_fromUtf8("cyphereTextLabel"))
        self.cypheredTextLayout.addWidget(self.cyphereTextLabel)
        self.cypheredTextLineEdit = QtGui.QLineEdit(self.plainTextAttackGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cypheredTextLineEdit.sizePolicy().hasHeightForWidth())
        self.cypheredTextLineEdit.setSizePolicy(sizePolicy)
        self.cypheredTextLineEdit.setObjectName(_fromUtf8("cypheredTextLineEdit"))
        self.cypheredTextLayout.addWidget(self.cypheredTextLineEdit)
        self.verticalLayout_2.addLayout(self.cypheredTextLayout)
        self.decypheredTextLayout = QtGui.QHBoxLayout()
        self.decypheredTextLayout.setObjectName(_fromUtf8("decypheredTextLayout"))
        self.decypheredTextLabel = QtGui.QLabel(self.plainTextAttackGroupBox)
        self.decypheredTextLabel.setObjectName(_fromUtf8("decypheredTextLabel"))
        self.decypheredTextLayout.addWidget(self.decypheredTextLabel)
        self.decypheredTextLineEdit = QtGui.QLineEdit(self.plainTextAttackGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decypheredTextLineEdit.sizePolicy().hasHeightForWidth())
        self.decypheredTextLineEdit.setSizePolicy(sizePolicy)
        self.decypheredTextLineEdit.setObjectName(_fromUtf8("decypheredTextLineEdit"))
        self.decypheredTextLayout.addWidget(self.decypheredTextLineEdit)
        self.verticalLayout_2.addLayout(self.decypheredTextLayout)
        self.keyLayout = QtGui.QHBoxLayout()
        self.keyLayout.setObjectName(_fromUtf8("keyLayout"))
        self.keyLabel = QtGui.QLabel(self.plainTextAttackGroupBox)
        self.keyLabel.setObjectName(_fromUtf8("keyLabel"))
        self.keyLayout.addWidget(self.keyLabel)
        self.keyResult = QtGui.QLineEdit(self.plainTextAttackGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyResult.sizePolicy().hasHeightForWidth())
        self.keyResult.setSizePolicy(sizePolicy)
        self.keyResult.setObjectName(_fromUtf8("keyResult"))
        self.keyLayout.addWidget(self.keyResult)
        self.verticalLayout_2.addLayout(self.keyLayout)
        self.verticalLayout_4.addWidget(self.plainTextAttackGroupBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        tabWidget.addTab(self.vigenere, _fromUtf8(""))
        self.substitutionTab = QtGui.QWidget()
        self.substitutionTab.setObjectName(_fromUtf8("substitutionTab"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.substitutionTab)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.textLayout = QtGui.QVBoxLayout()
        self.textLayout.setObjectName(_fromUtf8("textLayout"))
        self.cypheredTextGroupBox_SUB = QtGui.QGroupBox(self.substitutionTab)
        self.cypheredTextGroupBox_SUB.setObjectName(_fromUtf8("cypheredTextGroupBox_SUB"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.cypheredTextGroupBox_SUB)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.cypheredTextEdit_SUB = QtGui.QTextEdit(self.cypheredTextGroupBox_SUB)
        self.cypheredTextEdit_SUB.setObjectName(_fromUtf8("cypheredTextEdit_SUB"))
        self.horizontalLayout_13.addWidget(self.cypheredTextEdit_SUB)
        self.textLayout.addWidget(self.cypheredTextGroupBox_SUB)
        self.decypheredTextGroupBox_SUB = QtGui.QGroupBox(self.substitutionTab)
        self.decypheredTextGroupBox_SUB.setObjectName(_fromUtf8("decypheredTextGroupBox_SUB"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.decypheredTextGroupBox_SUB)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.decypheredTextEdit_SUB = QtGui.QTextEdit(self.decypheredTextGroupBox_SUB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decypheredTextEdit_SUB.sizePolicy().hasHeightForWidth())
        self.decypheredTextEdit_SUB.setSizePolicy(sizePolicy)
        self.decypheredTextEdit_SUB.setReadOnly(True)
        self.decypheredTextEdit_SUB.setObjectName(_fromUtf8("decypheredTextEdit_SUB"))
        self.horizontalLayout_18.addWidget(self.decypheredTextEdit_SUB)
        self.textLayout.addWidget(self.decypheredTextGroupBox_SUB)
        self.horizontalLayout_27.addLayout(self.textLayout)
        self.substitutionDictionnary = QtGui.QVBoxLayout()
        self.substitutionDictionnary.setObjectName(_fromUtf8("substitutionDictionnary"))
        self.letterLabelsLayout = QtGui.QHBoxLayout()
        self.letterLabelsLayout.setObjectName(_fromUtf8("letterLabelsLayout"))
        self.cypheredLaterLabel = QtGui.QLabel(self.substitutionTab)
        self.cypheredLaterLabel.setObjectName(_fromUtf8("cypheredLaterLabel"))
        self.letterLabelsLayout.addWidget(self.cypheredLaterLabel)
        self.clearLaterLabel = QtGui.QLabel(self.substitutionTab)
        self.clearLaterLabel.setObjectName(_fromUtf8("clearLaterLabel"))
        self.letterLabelsLayout.addWidget(self.clearLaterLabel)
        self.substitutionDictionnary.addLayout(self.letterLabelsLayout)
        self.letterLinesEditLayout = QtGui.QHBoxLayout()
        self.letterLinesEditLayout.setObjectName(_fromUtf8("letterLinesEditLayout"))
        self.cypheredLetterLineEdit = QtGui.QLineEdit(self.substitutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cypheredLetterLineEdit.sizePolicy().hasHeightForWidth())
        self.cypheredLetterLineEdit.setSizePolicy(sizePolicy)
        self.cypheredLetterLineEdit.setMaxLength(1)
        self.cypheredLetterLineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.cypheredLetterLineEdit.setObjectName(_fromUtf8("cypheredLetterLineEdit"))
        self.letterLinesEditLayout.addWidget(self.cypheredLetterLineEdit)
        self.decypheredLetterLineEdit = QtGui.QLineEdit(self.substitutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decypheredLetterLineEdit.sizePolicy().hasHeightForWidth())
        self.decypheredLetterLineEdit.setSizePolicy(sizePolicy)
        self.decypheredLetterLineEdit.setMaxLength(1)
        self.decypheredLetterLineEdit.setObjectName(_fromUtf8("decypheredLetterLineEdit"))
        self.letterLinesEditLayout.addWidget(self.decypheredLetterLineEdit)
        self.substitutionDictionnary.addLayout(self.letterLinesEditLayout)
        self.addSubstitutionButton = QtGui.QPushButton(self.substitutionTab)
        self.addSubstitutionButton.setObjectName(_fromUtf8("addSubstitutionButton"))
        self.substitutionDictionnary.addWidget(self.addSubstitutionButton)
        self.listOfSubstitutionLabel = QtGui.QLabel(self.substitutionTab)
        self.listOfSubstitutionLabel.setObjectName(_fromUtf8("listOfSubstitutionLabel"))
        self.substitutionDictionnary.addWidget(self.listOfSubstitutionLabel)
        self.substitutionList = QtGui.QListWidget(self.substitutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.substitutionList.sizePolicy().hasHeightForWidth())
        self.substitutionList.setSizePolicy(sizePolicy)
        self.substitutionList.setResizeMode(QtGui.QListView.Adjust)
        self.substitutionList.setObjectName(_fromUtf8("substitutionList"))
        self.substitutionDictionnary.addWidget(self.substitutionList)
        self.removeSelectedButton = QtGui.QPushButton(self.substitutionTab)
        self.removeSelectedButton.setObjectName(_fromUtf8("removeSelectedButton"))
        self.substitutionDictionnary.addWidget(self.removeSelectedButton)
        self.frequenciesTabWidget = QtGui.QTabWidget(self.substitutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequenciesTabWidget.sizePolicy().hasHeightForWidth())
        self.frequenciesTabWidget.setSizePolicy(sizePolicy)
        self.frequenciesTabWidget.setObjectName(_fromUtf8("frequenciesTabWidget"))
        self.letterTab = QtGui.QWidget()
        self.letterTab.setObjectName(_fromUtf8("letterTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.letterTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.englishLetterLabel = QtGui.QLabel(self.letterTab)
        self.englishLetterLabel.setTextFormat(QtCore.Qt.AutoText)
        self.englishLetterLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.englishLetterLabel.setObjectName(_fromUtf8("englishLetterLabel"))
        self.horizontalLayout_4.addWidget(self.englishLetterLabel)
        self.cypheredLetterLabel = QtGui.QLabel(self.letterTab)
        self.cypheredLetterLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cypheredLetterLabel.setObjectName(_fromUtf8("cypheredLetterLabel"))
        self.horizontalLayout_4.addWidget(self.cypheredLetterLabel)
        self.frenchLetterLabel = QtGui.QLabel(self.letterTab)
        self.frenchLetterLabel.setObjectName(_fromUtf8("frenchLetterLabel"))
        self.horizontalLayout_4.addWidget(self.frenchLetterLabel)
        self.frequenciesTabWidget.addTab(self.letterTab, _fromUtf8(""))
        self.digramTab = QtGui.QWidget()
        self.digramTab.setObjectName(_fromUtf8("digramTab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.digramTab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.englishDigramsLabel = QtGui.QLabel(self.digramTab)
        self.englishDigramsLabel.setObjectName(_fromUtf8("englishDigramsLabel"))
        self.horizontalLayout_5.addWidget(self.englishDigramsLabel)
        self.cypheredDigramsLabel = QtGui.QLabel(self.digramTab)
        self.cypheredDigramsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cypheredDigramsLabel.setObjectName(_fromUtf8("cypheredDigramsLabel"))
        self.horizontalLayout_5.addWidget(self.cypheredDigramsLabel)
        self.frenchDigramsLabel = QtGui.QLabel(self.digramTab)
        self.frenchDigramsLabel.setObjectName(_fromUtf8("frenchDigramsLabel"))
        self.horizontalLayout_5.addWidget(self.frenchDigramsLabel)
        self.frequenciesTabWidget.addTab(self.digramTab, _fromUtf8(""))
        self.trigramTab = QtGui.QWidget()
        self.trigramTab.setObjectName(_fromUtf8("trigramTab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.trigramTab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.englishTrigramsLabel = QtGui.QLabel(self.trigramTab)
        self.englishTrigramsLabel.setObjectName(_fromUtf8("englishTrigramsLabel"))
        self.horizontalLayout_6.addWidget(self.englishTrigramsLabel)
        self.cypheredTrigramsLabel = QtGui.QLabel(self.trigramTab)
        self.cypheredTrigramsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cypheredTrigramsLabel.setObjectName(_fromUtf8("cypheredTrigramsLabel"))
        self.horizontalLayout_6.addWidget(self.cypheredTrigramsLabel)
        self.frenchTrigramsLabel = QtGui.QLabel(self.trigramTab)
        self.frenchTrigramsLabel.setObjectName(_fromUtf8("frenchTrigramsLabel"))
        self.horizontalLayout_6.addWidget(self.frenchTrigramsLabel)
        self.frequenciesTabWidget.addTab(self.trigramTab, _fromUtf8(""))
        self.substitutionDictionnary.addWidget(self.frequenciesTabWidget)
        self.horizontalLayout_27.addLayout(self.substitutionDictionnary)
        tabWidget.addTab(self.substitutionTab, _fromUtf8(""))
        self.alphaShift = QtGui.QWidget()
        self.alphaShift.setObjectName(_fromUtf8("alphaShift"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.alphaShift)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.cypheredTextGroupBox_SHI = QtGui.QGroupBox(self.alphaShift)
        self.cypheredTextGroupBox_SHI.setObjectName(_fromUtf8("cypheredTextGroupBox_SHI"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.cypheredTextGroupBox_SHI)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.cypheredTextEdit_SHI = QtGui.QTextEdit(self.cypheredTextGroupBox_SHI)
        self.cypheredTextEdit_SHI.setObjectName(_fromUtf8("cypheredTextEdit_SHI"))
        self.horizontalLayout_14.addWidget(self.cypheredTextEdit_SHI)
        self.verticalLayout_7.addWidget(self.cypheredTextGroupBox_SHI)
        self.keyGroupBox_SHI = QtGui.QGroupBox(self.alphaShift)
        self.keyGroupBox_SHI.setObjectName(_fromUtf8("keyGroupBox_SHI"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.keyGroupBox_SHI)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.asciiOffsetLabel_SHI = QtGui.QLabel(self.keyGroupBox_SHI)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asciiOffsetLabel_SHI.sizePolicy().hasHeightForWidth())
        self.asciiOffsetLabel_SHI.setSizePolicy(sizePolicy)
        self.asciiOffsetLabel_SHI.setObjectName(_fromUtf8("asciiOffsetLabel_SHI"))
        self.horizontalLayout_23.addWidget(self.asciiOffsetLabel_SHI)
        self.asciiOffsetSpinBox_SHI = QtGui.QSpinBox(self.keyGroupBox_SHI)
        self.asciiOffsetSpinBox_SHI.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.asciiOffsetSpinBox_SHI.setMinimum(-255)
        self.asciiOffsetSpinBox_SHI.setMaximum(255)
        self.asciiOffsetSpinBox_SHI.setObjectName(_fromUtf8("asciiOffsetSpinBox_SHI"))
        self.horizontalLayout_23.addWidget(self.asciiOffsetSpinBox_SHI)
        self.verticalLayout_7.addWidget(self.keyGroupBox_SHI)
        self.decypheredTextGroupBox_SHI = QtGui.QGroupBox(self.alphaShift)
        self.decypheredTextGroupBox_SHI.setObjectName(_fromUtf8("decypheredTextGroupBox_SHI"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.decypheredTextGroupBox_SHI)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.decypheredTextEdit_SHI = QtGui.QTextEdit(self.decypheredTextGroupBox_SHI)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decypheredTextEdit_SHI.sizePolicy().hasHeightForWidth())
        self.decypheredTextEdit_SHI.setSizePolicy(sizePolicy)
        self.decypheredTextEdit_SHI.setObjectName(_fromUtf8("decypheredTextEdit_SHI"))
        self.horizontalLayout_19.addWidget(self.decypheredTextEdit_SHI)
        self.verticalLayout_7.addWidget(self.decypheredTextGroupBox_SHI)
        tabWidget.addTab(self.alphaShift, _fromUtf8(""))
        self.hashTab = QtGui.QWidget()
        self.hashTab.setObjectName(_fromUtf8("hashTab"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.hashTab)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.webView_2 = QtWebKit.QWebView(self.hashTab)
        self.webView_2.setUrl(QtCore.QUrl(_fromUtf8("http://home.paulschou.net/tools/xlate/")))
        self.webView_2.setObjectName(_fromUtf8("webView_2"))
        self.horizontalLayout_8.addWidget(self.webView_2)
        tabWidget.addTab(self.hashTab, _fromUtf8(""))
        self.polybeTab = QtGui.QWidget()
        self.polybeTab.setObjectName(_fromUtf8("polybeTab"))
        self.gridLayout = QtGui.QGridLayout(self.polybeTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.polybeTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.polybeTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_10.addWidget(self.lineEdit_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.polybeTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        tabWidget.addTab(self.polybeTab, _fromUtf8(""))

        self.retranslateUi(tabWidget)
        tabWidget.setCurrentIndex(0)
        self.frequenciesTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(tabWidget)

    def retranslateUi(self, tabWidget):
        tabWidget.setWindowTitle(_translate("tabWidget", "TabWidget", None))
        self.cypheredGroupBox_VIG.setTitle(_translate("tabWidget", "Cyphered Text", None))
        self.bruteForceGroupBox.setTitle(_translate("tabWidget", "BruteForce tools", None))
        self.bruteForceButton.setText(_translate("tabWidget", "BruteForce", None))
        self.lengthFoundLabel.setText(_translate("tabWidget", "Length found :", None))
        self.languageComboBox.setItemText(0, _translate("tabWidget", "EN", None))
        self.languageComboBox.setItemText(1, _translate("tabWidget", "FR", None))
        self.languageComboBox.setItemText(2, _translate("tabWidget", "DE", None))
        self.languageComboBox.setItemText(3, _translate("tabWidget", "IT", None))
        self.languageComboBox.setItemText(4, _translate("tabWidget", "PT", None))
        self.languageComboBox.setItemText(5, _translate("tabWidget", "ES", None))
        self.keyFoundLabel.setText(_translate("tabWidget", "Key found :", None))
        self.tryKeyButton.setText(_translate("tabWidget", "Try", None))
        self.keyGroupBox.setTitle(_translate("tabWidget", "Key", None))
        self.keyOffsetLabel.setText(_translate("tabWidget", "Key Offset :", None))
        self.decypheredTextGroupBox_VIG.setTitle(_translate("tabWidget", "Decyphered Text", None))
        self.groupBox_4.setTitle(_translate("tabWidget", "Decyphered Text Options", None))
        self.checkBox_2.setText(_translate("tabWidget", "Display Text", None))
        self.checkBox.setText(_translate("tabWidget", "Display Key", None))
        self.plainTextAttackGroupBox.setTitle(_translate("tabWidget", "Plain Text Attack ", None))
        self.cyphereTextLabel.setText(_translate("tabWidget", "Cyphered Text:", None))
        self.decypheredTextLabel.setText(_translate("tabWidget", "Decyphered Text:", None))
        self.keyLabel.setText(_translate("tabWidget", "Key :", None))
        tabWidget.setTabText(tabWidget.indexOf(self.vigenere), _translate("tabWidget", "Vigenere", None))
        self.cypheredTextGroupBox_SUB.setTitle(_translate("tabWidget", "Cyphered Text", None))
        self.decypheredTextGroupBox_SUB.setTitle(_translate("tabWidget", "Decyphered Text", None))
        self.cypheredLaterLabel.setText(_translate("tabWidget", "Cyphered Letter: :", None))
        self.clearLaterLabel.setText(_translate("tabWidget", "Clear Letter :", None))
        self.addSubstitutionButton.setText(_translate("tabWidget", "Add Subtitution", None))
        self.listOfSubstitutionLabel.setText(_translate("tabWidget", "List of Subtitution :", None))
        self.substitutionList.setSortingEnabled(True)
        self.removeSelectedButton.setText(_translate("tabWidget", "Remove Selected", None))
        self.englishLetterLabel.setText(_translate("tabWidget", "English", None))
        self.cypheredLetterLabel.setText(_translate("tabWidget", "Cyphered", None))
        self.frenchLetterLabel.setText(_translate("tabWidget", "French", None))
        self.frequenciesTabWidget.setTabText(self.frequenciesTabWidget.indexOf(self.letterTab), _translate("tabWidget", "Letter", None))
        self.englishDigramsLabel.setText(_translate("tabWidget", "English", None))
        self.cypheredDigramsLabel.setText(_translate("tabWidget", "Cyphered", None))
        self.frenchDigramsLabel.setText(_translate("tabWidget", "French", None))
        self.frequenciesTabWidget.setTabText(self.frequenciesTabWidget.indexOf(self.digramTab), _translate("tabWidget", "Digram", None))
        self.englishTrigramsLabel.setText(_translate("tabWidget", "English", None))
        self.cypheredTrigramsLabel.setText(_translate("tabWidget", "Cyphered", None))
        self.frenchTrigramsLabel.setText(_translate("tabWidget", "French", None))
        self.frequenciesTabWidget.setTabText(self.frequenciesTabWidget.indexOf(self.trigramTab), _translate("tabWidget", "Trigram", None))
        tabWidget.setTabText(tabWidget.indexOf(self.substitutionTab), _translate("tabWidget", "Alphabetical Subtitution", None))
        self.cypheredTextGroupBox_SHI.setTitle(_translate("tabWidget", "Cyphered Text", None))
        self.keyGroupBox_SHI.setTitle(_translate("tabWidget", "Key", None))
        self.asciiOffsetLabel_SHI.setText(_translate("tabWidget", "ASCII Offset :", None))
        self.decypheredTextGroupBox_SHI.setTitle(_translate("tabWidget", "Decyphered Text", None))
        tabWidget.setTabText(tabWidget.indexOf(self.alphaShift), _translate("tabWidget", "Alphabetical Shifting", None))
        tabWidget.setTabText(tabWidget.indexOf(self.hashTab), _translate("tabWidget", "HASHES", None))
        self.groupBox.setTitle(_translate("tabWidget", "Code des Templiers", None))
        self.label_3.setText(_translate("tabWidget", "ImageCodeTemplier", None))
        self.groupBox_2.setTitle(_translate("tabWidget", "Polybe/Téléphone", None))
        self.label_5.setText(_translate("tabWidget", "Text Chiffré :", None))
        self.label_6.setText(_translate("tabWidget", "Polybe :", None))
        self.label.setText(_translate("tabWidget", "Téléphone", None))
        self.groupBox_3.setTitle(_translate("tabWidget", "Code Morpion (Franc Maçon)", None))
        self.label_4.setText(_translate("tabWidget", "ImageCodeMorpion", None))
        tabWidget.setTabText(tabWidget.indexOf(self.polybeTab), _translate("tabWidget", "Divers", None))

from PyQt4 import QtWebKit
